#pragma once
#include <PrimitiveTypes.h>

namespace MarkTech
{
	enum class Keycode : U8
	{
		BACKQUOTE,
		ONE,TWO,THREE,FOUR,FIVE,SIX,SEVEN,EIGHT,NINE,ZERO,
		BACKSPACE,
		TAB,
		Q,W,E,R,T,Y,U,I,O,P,
		LEFT_BRACKET,RIGHT_BRACKET,
		BACKSLASH,
		CAPSLOCK,
		A,S,D,F,G,H,J,K,L,
		SEMICOLON,
		QUOTE,
		ENTER,
		LEFT_SHIFT,
		Z,X,C,V,B,N,M,
		COMMA,
		PERIOD,
		SLASH,
		RIGHT_SHIFT,
		LEFT_CONTROL,
		LEFT_ALT,
		SPACEBAR,
		RIGHT_ALT,
		RIGHT_CONTROL,
		UP,DOWN,LEFT,RIGHT,
		ESCAPE,
		F1,F2,F3,F4,F5,F6,F7,F8,F9,F10,F11,F12
	};
}